<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $records = [
            [
                'id' => 1,
                'program_project_activity' => 'ADAPTIVE CAPACITIES OF HUMAN COMMUNITIES AND NATURAL SYSTEMS IMPROVED',
                'output_indicators' => null,
                'office' => null,
                'universe' => null,
                'accomplishment' => null,
                'order_column' => 1,
                'parent_id' => null,
                'record_type' => 'program',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'program_project_activity' => 'Environment and Natural Resources Resiliency Program',
                'output_indicators' => null,
                'office' => null,
                'universe' => null,
                'accomplishment' => null,
                'order_column' => 2,
                'parent_id' => null,
                'record_type' => 'project',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'program_project_activity' => 'Climate Risk Vulnerability Assessement (CRVA)',
                'output_indicators' => null,
                'office' => 'RO',
                'universe' => 0,
                'accomplishment' => 0,
                'order_column' => 3,
                'parent_id' => null,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),                
            ],
            [
                'id' => 4,
                'program_project_activity' => 'Establishment and measurement of FRA tracts',
                'output_indicators' => 'FRA tracts established and measured',
                'office' => 'RO',
                'universe' => 10,
                'accomplishment' => 5,
                'order_column' => 4,
                'parent_id' => null,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'program_project_activity' => 'Climate Change Related Activities (Risk Resiliency Program)',
                'output_indicators' => null,
                'office' => 'RO',
                'universe' => 0,
                'accomplishment' => 0,
                'order_column' => 5,
                'parent_id' => null,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'program_project_activity' => 'Opratiorationalization of the RRP Regional TWG',
                'output_indicators' => 'TWG meetings conducted (No.)',
                'office' => 'RO',
                'universe' => 2,
                'accomplishment' => 1,
                'order_column' => 6,
                'parent_id' => 5,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'program_project_activity' => 'Review and evaluation of PAPs from the IPRRs',
                'output_indicators' => 'PAPs reviewed and evaluated by the RTWG (No.)',
                'office' => 'RO',
                'universe' => 1,
                'accomplishment' => 1,
                'order_column' => 7,
                'parent_id' => 5,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'program_project_activity' => 'Assessment (using the Green Assessment and Recovery Framework) in case of disasters (eg. typhoons)',
                'output_indicators' => 'Post-disaster situational reports prepared (No.)',
                'office' => 'RO',
                'universe' => 1,
                'accomplishment' => 1,
                'order_column' => 8,
                'parent_id' => 5,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'program_project_activity' => 'Fix Expenditure and Mandatories',
                'output_indicators' => null,
                'office' => 'RO',
                'universe' => null,
                'accomplishment' => null,
                'order_column' => 9,
                'parent_id' => null,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'program_project_activity' => 'OSEC Fund',
                'output_indicators' => null,
                'office' => 'RO',
                'universe' => 5,
                'accomplishment' => 5,
                'order_column' => 10,
                'parent_id' => 9,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,  
                'program_project_activity' => 'Youth/Senior/PWD Fund',
                'output_indicators' => null,
                'office' => 'RO',
                'universe' => null,
                'accomplishment' => null,
                'order_column' => 11,
                'parent_id' => 9,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,  
                'program_project_activity' => 'PMS',
                'output_indicators' => null,
                'office' => 'RO',
                'universe' => 15,
                'accomplishment' => 15,
                'order_column' => 12,
                'parent_id' => 9,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,  
                'program_project_activity' => 'Support to Regional GAD Focal Point System',
                'output_indicators' => null,
                'office' => 'RO',
                'universe' => 15,
                'accomplishment' => 15,
                'order_column' => 13,
                'parent_id' => 9,
                'record_type' => 'activity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('nra')->insert($records);
    }
}
